#!/bin/bash

echo "🔥 Adding Firebase Dependencies to liquid-glass-play"
echo "Please follow these steps in Xcode:"
echo ""
echo "1. Open liquid-glass-play.xcodeproj in Xcode"
echo "2. Select the liquid-glass-play project in the navigator"
echo "3. Select the liquid-glass-play target"
echo "4. Go to 'Package Dependencies' tab"
echo "5. Click the '+' button to add package dependency"
echo "6. Enter this URL: https://github.com/firebase/firebase-ios-sdk"
echo "7. Click 'Add Package'"
echo "8. Select these Firebase products:"
echo "   - FirebaseAuth"
echo "   - FirebaseFirestore"
echo "   - FirebaseCore"
echo "9. Click 'Add Package'"
echo ""
echo "10. Google Sign-In is enabled through Firebase Auth"
echo "    (No additional packages needed for Google authentication)"
echo ""
echo "📝 Manual steps needed:"
echo "1. Add GoogleService-Info.plist to project target"
echo "2. Build and run the project"
echo ""
echo "✅ Firebase integration should be complete!"

# Make the script executable
chmod +x "$0" 